example.organization.property: "I AM THE DEFAULT"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/SPRING_CLOUD_CHAPTER6"
spring.datasource.username: "root"
spring.datasource.password: "zww.CUIHUA"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQLDialect"